// constants/con.jsx

import pr2 from '../assets/images/pr2.jpg';
import pr3 from '../assets/images/pr3.jpg';

export const trendingBlogs = [
  {
    id: 1,
    author: 'John Doe',
    authorProfile: pr2,
    authorDescription: 'Inventor of the World Wide Web (WWW) and the co-founder and Chief Technology Officer (CTO) of Inrupt.com. He leads the Solid project and is a co-founder of the Web Foundation, as well as the Open Data Institute (ODI). Tim is an Emeritus Professor of Computer Science at MIT and Oxford University.',
    authorFollowers: '234',
    date: '2024-03-20T12:00:00Z',
    title: "React Hooks: A Beginner's Guide",
    description: 'Learn how to use React Hooks to enhance your React applications.',
    image: 'https://example.com/blog-image.jpg',
    publishedDate: '2024-03-18T10:30:00Z',
    readTime: 54,
  },
  {
    id: 2,
    author: 'John Doe',
    authorProfile: pr3,
    authorDescription: 'Inventor of the World Wide Web (WWW) and the co-founder and Chief Technology Officer (CTO) of Inrupt.com. He leads the Solid project and is a co-founder of the Web Foundation, as well as the Open Data Institute (ODI). Tim is an Emeritus Professor of Computer Science at MIT and Oxford University.',
    authorFollowers: '234',
    date: '2024-03-10T12:00:00Z',
    title: 'Getting Started with Tailwind CSS',
    description: 'Learn how to use Tailwind CSS to create responsive and beautiful designs.',
    image: 'https://example.com/blog2.jpg',
    publishedDate: '2024-03-08T10:30:00Z',
    readTime: 54,
  },
  {
    id: 3,
    author: 'John Doe',
    authorProfile: pr2,
    authorDescription: 'Inventor of the World Wide Web (WWW) and the co-founder and Chief Technology Officer (CTO) of Inrupt.com. He leads the Solid project and is a co-founder of the Web Foundation, as well as the Open Data Institute (ODI). Tim is an Emeritus Professor of Computer Science at MIT and Oxford University.',
    authorFollowers: '234',
    date: '2024-03-10T12:00:00Z',
    title: 'Getting Started with Tailwind CSS',
    description: 'Learn how to use Tailwind CSS to create responsive and beautiful designs.',
    image: 'https://example.com/blog2.jpg',
    publishedDate: '2024-03-08T10:30:00Z',
    readTime: 54,
  },
  // Add more trending blog objects as needed
];

export const blogs = [
  {
    id: 1,
    author: 'John Doe',
    authorProfile: pr2, // Using the author profile image from assets folder
    authorDescription: 'Inventor of the World Wide Web (WWW) and the co-founder and Chief Technology Officer (CTO) of Inrupt.com. He leads the Solid project and is a co-founder of the Web Foundation, as well as the Open Data Institute (ODI). Tim is an Emeritus Professor of Computer Science at MIT and Oxford University.',
    authorFollowers: '234',
    date: '2024-03-20T12:00:00Z',
    title: "React Hooks: A Beginner's Guide",
    description: 'Learn how to use React Hooks to enhance your React applications.',
    image: 'https://example.com/blog-image.jpg',
    publishedDate: '2024-03-18T10:30:00Z',
    readTime: 54,
  },
  {
    id: 2,
    author: 'John Doe',
    authorProfile: pr3, // Using the author profile image from assets folder
    authorDescription: 'Inventor of the World Wide Web (WWW) and the co-founder and Chief Technology Officer (CTO) of Inrupt.com. He leads the Solid project and is a co-founder of the Web Foundation, as well as the Open Data Institute (ODI). Tim is an Emeritus Professor of Computer Science at MIT and Oxford University.',
    authorFollowers: '234',
    date: '2024-03-10T12:00:00Z',
    title: 'Getting Started with Tailwind CSS',
    description: 'Learn how to use Tailwind CSS to create responsive and beautiful designs.',
    image: 'https://example.com/blog2.jpg',
    publishedDate: '2024-03-08T10:30:00Z',
    readTime: 54,
  },
  // Add more blog objects as needed
];
export const words =[
  'Web Development',
  'Mobile App Development',
  'Machine Learning',
  'Artificial Intelligence',
  'Data Science',
  'Cloud Computing',
  'Cybersecurity',
  'Product Management',
  'UI/UX Design',
  'Software Engineering',
  'Tech Events',
  'Programming Languages',
  'Open Source',
  'DevOps',
  'Agile Methodology',
  'Career Development',
  'Blockchain',
  'Internet of Things (IoT)',
  'Augmented Reality (AR)',
  'Virtual Reality (VR)',
  'Robotics',
  'Quantum Computing',
  'Data Analytics',
  'Digital Marketing',
  'Entrepreneurship',
  'Startup Ecosystem',
  'Tech News',
  'Industry Trends',
  'Code Optimization',
  'Software Testing',
  'Game Development',
  'User Experience (UX)',
  'User Interface (UI)',
  'Frontend Development',
  'Backend Development',
  'Full-Stack Development',
  'API Development',
  'Mobile Design',
  'Cloud Services',
  'Data Visualization',
  'Network Security',
  'Privacy Concerns',
  'Tech Tools',
  'Project Management',
  'Remote Work',
  'Tech Communities',
  'Tech Leadership',
  'Tech Interviews',
  'Digital Transformation',
  'Tech for Social Good',
];